/**
 * PDF Templates
 *
 * Shared styling constants and formatting utilities for PDF report generation.
 * Provides consistent branding and layout for accessibility reports.
 */

import PDFDocument from 'pdfkit';

// PDFDocument instance type - exported for use in other modules
export type PDFDocumentInstance = InstanceType<typeof PDFDocument>;

/**
 * Brand colors for ADAShield reports
 */
export const COLORS = {
  /** Primary brand color - ADAShield blue */
  primary: '#2563EB',
  /** Dark text color for body content */
  text: '#1F2937',
  /** Light gray for secondary text */
  textSecondary: '#6B7280',
  /** Background gray for sections */
  background: '#F3F4F6',
  /** Border color */
  border: '#E5E7EB',
  /** Critical severity - Red */
  critical: '#DC2626',
  /** Serious severity - Orange */
  serious: '#EA580C',
  /** Moderate severity - Yellow */
  moderate: '#CA8A04',
  /** Minor severity - Blue */
  minor: '#2563EB',
  /** Success/passed color - Green */
  success: '#16A34A',
} as const;

/**
 * Font sizes for consistent typography
 */
export const FONTS = {
  title: 24,
  heading: 18,
  subheading: 14,
  body: 11,
  small: 9,
} as const;

/**
 * Layout spacing constants
 */
export const SPACING = {
  margin: 50,
  sectionGap: 20,
  lineGap: 8,
  smallGap: 4,
} as const;

/**
 * Page dimensions (Letter size)
 */
export const PAGE = {
  width: 612,
  height: 792,
  contentWidth: 512, // width - (2 * margin)
} as const;

/**
 * Severity display configuration
 */
export interface SeverityConfig {
  label: string;
  color: string;
}

export const SEVERITY_CONFIG: Record<string, SeverityConfig> = {
  critical: { label: 'CRITICAL', color: COLORS.critical },
  serious: { label: 'SERIOUS', color: COLORS.serious },
  moderate: { label: 'MODERATE', color: COLORS.moderate },
  minor: { label: 'MINOR', color: COLORS.minor },
} as const;

/**
 * Add a styled header to the PDF
 */
export function addHeader(doc: PDFDocumentInstance, title: string): void {
  doc
    .fontSize(FONTS.title)
    .fillColor(COLORS.primary)
    .text(title, { align: 'center' })
    .moveDown(0.5);
}

/**
 * Add a section heading with optional background
 */
export function addSectionHeading(doc: PDFDocumentInstance, text: string, background = false): void {
  if (background) {
    const y = doc.y;
    doc
      .rect(SPACING.margin, y - 5, PAGE.contentWidth, FONTS.heading + 10)
      .fill(COLORS.background);
    doc.y = y; // Reset Y position after drawing rectangle
  }

  doc
    .fontSize(FONTS.heading)
    .fillColor(COLORS.text)
    .text(text)
    .moveDown(0.5);
}

/**
 * Add a horizontal divider line
 */
export function addDivider(doc: PDFDocumentInstance): void {
  const y = doc.y;
  doc
    .moveTo(SPACING.margin, y)
    .lineTo(PAGE.width - SPACING.margin, y)
    .strokeColor(COLORS.border)
    .stroke();
  doc.moveDown(0.5);
}

/**
 * Add a two-column info row (label: value)
 */
export function addInfoRow(doc: PDFDocumentInstance, label: string, value: string): void {
  const y = doc.y;

  doc
    .fontSize(FONTS.body)
    .fillColor(COLORS.textSecondary)
    .text(label, SPACING.margin, y, { continued: false, width: 150 });

  doc
    .fillColor(COLORS.text)
    .text(value, SPACING.margin + 160, y);

  doc.moveDown(0.3);
}

/**
 * Add a severity badge with colored indicator
 */
export function addSeverityBadge(
  doc: PDFDocumentInstance,
  severity: string,
  count: number,
  x: number,
  y: number,
  width = 120
): void {
  const config = SEVERITY_CONFIG[severity.toLowerCase()];
  if (!config) return;

  // Draw colored rectangle
  doc
    .rect(x, y, 4, 20)
    .fill(config.color);

  // Draw label and count
  doc
    .fontSize(FONTS.body)
    .fillColor(COLORS.text)
    .text(`${config.label}:`, x + 10, y + 3, { width: width - 50, continued: true })
    .font('Helvetica-Bold')
    .text(` ${count}`);

  doc.font('Helvetica'); // Reset font
}

/**
 * Add a disclaimer box with light background
 */
export function addDisclaimerBox(doc: PDFDocumentInstance, text: string): void {
  const y = doc.y;
  const boxHeight = 60;

  // Draw background
  doc
    .rect(SPACING.margin, y, PAGE.contentWidth, boxHeight)
    .fill(COLORS.background);

  // Add text
  doc
    .fontSize(FONTS.small)
    .fillColor(COLORS.textSecondary)
    .text(text, SPACING.margin + 10, y + 10, {
      width: PAGE.contentWidth - 20,
      align: 'left',
    });

  doc.y = y + boxHeight;
  doc.moveDown(0.5);
}

/**
 * Add footer with branding and page number
 * Uses lineBreak: false to prevent PDFKit from adding new pages
 */
export function addFooter(doc: PDFDocumentInstance, pageNumber: number): void {
  // Save current position to restore after adding footer
  const savedY = doc.y;
  const bottomY = PAGE.height - 40;

  // Add branding on the left - use lineBreak: false to prevent page overflow
  doc
    .fontSize(FONTS.small)
    .fillColor(COLORS.textSecondary)
    .text(
      'Generated by ADAShield - https://adashield.io',
      SPACING.margin,
      bottomY,
      { lineBreak: false }
    );

  // Add page number on the right - calculate exact position
  const pageText = `Page ${pageNumber}`;
  const pageTextWidth = doc.widthOfString(pageText);
  doc.text(
    pageText,
    PAGE.width - SPACING.margin - pageTextWidth,
    bottomY,
    { lineBreak: false }
  );

  // Restore Y position so footer doesn't affect content flow
  doc.y = savedY;
}

/**
 * Format a date for display in the PDF
 */
export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  }).format(date);
}

/**
 * Format duration in milliseconds to human-readable string
 */
export function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${ms}ms`;
  }
  const seconds = Math.floor(ms / 1000);
  if (seconds < 60) {
    return `${seconds}s`;
  }
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}m ${remainingSeconds}s`;
}

/**
 * Truncate text to a maximum length with ellipsis
 */
export function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return text.substring(0, maxLength - 3) + '...';
}

/**
 * Check if there's enough space on the current page
 * If not, add a new page
 */
export function ensureSpace(doc: PDFDocumentInstance, requiredSpace: number): void {
  if (doc.y + requiredSpace > PAGE.height - 60) {
    doc.addPage();
  }
}
