/**
 * AiIssueEnhancement Component Tests
 *
 * Tests for the AI issue enhancement component with the new formatter integration.
 * Covers rendering, loading states, priority indicators, and formatted content.
 *
 * Requirements: 6.2, 6.3, 6.4
 */

import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { AiIssueEnhancement, AiIssueData } from './AiIssueEnhancement';

describe('AiIssueEnhancement', () => {
  const mockData: AiIssueData = {
    issueId: 'test-issue-1',
    explanation: 'This image is missing an `alt` attribute.',
    fixSuggestion:
      'Add an alt attribute to describe the image.\n\nBefore:\n```html\n<img src="photo.jpg">\n```\n\nAfter:\n```html\n<img src="photo.jpg" alt="A photo of sunset">\n```',
    priority: 8,
  };

  describe('Loading state', () => {
    it('should show loading skeleton when isLoading is true', () => {
      render(<AiIssueEnhancement isLoading={true} />);

      expect(screen.getByRole('status')).toBeInTheDocument();
      expect(screen.getByText('AI insights loading...')).toBeInTheDocument();
    });

    it('should show loading skeleton when data is undefined', () => {
      render(<AiIssueEnhancement data={undefined} />);

      expect(screen.getByRole('status')).toBeInTheDocument();
    });

    it('should show loading skeleton when data is null', () => {
      render(<AiIssueEnhancement data={null} />);

      expect(screen.getByRole('status')).toBeInTheDocument();
    });
  });

  describe('Content rendering', () => {
    it('should render AI-Enhanced Analysis header', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(screen.getByText('AI-Enhanced Analysis')).toBeInTheDocument();
    });

    it('should render "What This Means" section', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(screen.getByText('What This Means')).toBeInTheDocument();
    });

    it('should render "How to Fix It" section', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(screen.getByText('How to Fix It')).toBeInTheDocument();
    });

    it('should render explanation content with formatted code', () => {
      render(<AiIssueEnhancement data={mockData} />);

      // The explanation should contain the inline code
      expect(screen.getByText('alt')).toBeInTheDocument();
    });

    it('should render fix suggestion with code blocks', () => {
      render(<AiIssueEnhancement data={mockData} />);

      // Should find the code content (appears in both Before and After sections)
      const codeElements = screen.getAllByText(/img src="photo.jpg"/);
      expect(codeElements.length).toBeGreaterThanOrEqual(1);
    });

    it('should render AI attribution notice', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(
        screen.getByText(/Generated by AI - Review recommendations carefully/)
      ).toBeInTheDocument();
    });
  });

  describe('Priority indicator', () => {
    it('should show Critical for priority >= 8', () => {
      render(<AiIssueEnhancement data={{ ...mockData, priority: 8 }} />);

      expect(screen.getByText('Critical')).toBeInTheDocument();
      expect(screen.getByText('8/10')).toBeInTheDocument();
    });

    it('should show High for priority 6-7', () => {
      render(<AiIssueEnhancement data={{ ...mockData, priority: 6 }} />);

      expect(screen.getByText('High')).toBeInTheDocument();
      expect(screen.getByText('6/10')).toBeInTheDocument();
    });

    it('should show Medium for priority 4-5', () => {
      render(<AiIssueEnhancement data={{ ...mockData, priority: 5 }} />);

      expect(screen.getByText('Medium')).toBeInTheDocument();
      expect(screen.getByText('5/10')).toBeInTheDocument();
    });

    it('should show Low for priority <= 3', () => {
      render(<AiIssueEnhancement data={{ ...mockData, priority: 3 }} />);

      expect(screen.getByText('Low')).toBeInTheDocument();
      expect(screen.getByText('3/10')).toBeInTheDocument();
    });

    it('should have correct aria-label for priority', () => {
      render(<AiIssueEnhancement data={{ ...mockData, priority: 8 }} />);

      const priorityElement = screen.getByRole('status', {
        name: /Priority: Critical \(8 out of 10\)/,
      });
      expect(priorityElement).toBeInTheDocument();
    });
  });

  describe('Formatted content', () => {
    it('should render Before: section from fix suggestion', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(screen.getByText(/Before:/)).toBeInTheDocument();
    });

    it('should render After: section from fix suggestion', () => {
      render(<AiIssueEnhancement data={mockData} />);

      expect(screen.getByText(/After:/)).toBeInTheDocument();
    });

    it('should render URLs as clickable links', () => {
      const dataWithUrl: AiIssueData = {
        ...mockData,
        fixSuggestion:
          'Check https://webaim.org/resources/contrastchecker/ for more info.',
      };

      render(<AiIssueEnhancement data={dataWithUrl} />);

      const link = screen.getByRole('link', {
        name: /webaim.org\/resources\/contrastchecker/,
      });
      expect(link).toBeInTheDocument();
      expect(link).toHaveAttribute(
        'href',
        'https://webaim.org/resources/contrastchecker/'
      );
      expect(link).toHaveAttribute('target', '_blank');
      expect(link).toHaveAttribute('rel', 'noopener noreferrer');
    });
  });

  describe('Accessibility', () => {
    it('should have aria-hidden on decorative sparkles icon', () => {
      render(<AiIssueEnhancement data={mockData} />);

      // The sparkles icon should be aria-hidden
      const container = document.querySelector('svg[aria-hidden="true"]');
      expect(container).toBeInTheDocument();
    });

    it('should have proper heading hierarchy', () => {
      render(<AiIssueEnhancement data={mockData} />);

      const headings = screen.getAllByRole('heading', { level: 4 });
      expect(headings).toHaveLength(2);
      expect(headings[0]).toHaveTextContent('What This Means');
      expect(headings[1]).toHaveTextContent('How to Fix It');
    });
  });
});
